export const chars = {
  square1: '░',
  square2: '▒',
  square3: '▓',
  squareFull: '█',
  squareLow: '▄',
  squareCenter: '■',
  squareHigh: '▀',
  doubleLineA: '║',
  doubleLineB: '═',
  doubleLineCornerA: '╗',
  doubleLineCornerB: '╝',
  doubleLineCornerC: '╚',
  doubleLineCornerD: '╔',
  doubleLineT1: '╣',
  doubleLineT2: '╩',
  doubleLineT3: '╦',
  doubleLineT4: '╠',
  doubleLine4Way: '╬',
  singleLineA: '│',
  singleLineB: '─',
  singleLineCornerA: '┌',
  singleLineCornerB: '┘',
  singleLineCornerC: '┐',
  singleLineCornerD: '└',
  singleLineT1: '┤',
  singleLineT2: '┴',
  singleLineT3: '┬',
  singleLineT4: '├',
  singleLine4Way: '┼',
};

export const sep = '\n';